{
	"targets": [{
		"target_name": "ECIES",
		"sources": [
			"app.cc",
			"node_ecies_wrapper.cc",
			"ecc.c",
			"hex.c",
			# "apps/myApps/RPi_VREX/src/EyeTracker/EyeTracker.cpp",
			# "apps/myApps/RPi_VREX/src/EyeTracker/Calibration.cpp",
			# "apps/myApps/RPi_VREX/src/EyeTracker/imageProc/PupilDetector.cpp",
			# "apps/myApps/RPi_VREX/src/EyeTracker/imageProc/RobustPupilDetector.cpp",
			# "apps/myApps/RPi_VREX/src/EyeTracker/imageProc/VCRansac.cpp",
			# "apps/myApps/RPi_VREX/src/EyeTracker/utils/VCAndroidTool.cpp",
			# "apps/myApps/RPi_VREX/src/EyeTracker/utils/VCFilter.cpp",
			# "apps/myApps/RPi_VREX/src/EyeTracker/utils/UVCCamera.cpp",
		],
		"include_dirs": [
			"<!(node -e \"require('nan')\")",
			# "libs/openFrameworks",
			# "libs/openFrameworks/utils",
			# "libs/openFrameworks/types",
			# "libs/openFrameworks/math",
			# "libs/openFrameworks/events",
			# "libs/openFrameworks/3d",
			# "libs/openFrameworks/gl",
			# "libs/openFrameworks/graphics",
			# "libs/openFrameworks/communication",
			# "libs/openFrameworks/app",
			# "libs/openFrameworks/video",
			# "libs/utf8cpp/include",
			# "libs/tess2/include",
			# "libs/glfw/include",
			# "libs/openFrameworks/sound",
			# "libs/kiss/include",
			# "/usr/include/cairo",
			# "/usr/include/gstreamer-1.0",
			# "/usr/include/glib-2.0",
			# "apps/myApps/RPi_VREX/src",
			# "apps/myApps/RPi_VREX/src/EyeTracker",
			# "apps/myApps/RPi_VREX/src/EyeTracker/imageProc",
			# "apps/myApps/RPi_VREX/src/EyeTracker/utils",
			# "addons/ofxOpenCv/src",
			# "addons/ofxOpenCv/libs/opencv/include/opencv",
			# "addons/ofxopenCv/libs/opencv/include/opencv2/imgproc",
			# "addons/ofxXmlSettings/src",
			# "addons/ofxXmlSettings/libs",
		],
		"libraries": [
			# "-luvc",
			# "/home/pi/node-oF/libs/openFrameworksCompiled/lib/linuxarmv6l/libopenFrameworks.a",
			# "/home/pi/node-oF/libs/freetype/lib/linuxarmv6l/libfreetype.a",
			# "-lboost_system",
			# "-lPocoNet",
			# "-lopencv_imgproc",
			# "-lopencv_core",
		],
		"cflags_cc!": [ "-fno-rtti", "-fno-exceptions" ],
		"cflags": [ 
			# "-D__VREX__",
			# "-std=c++11" 
			]
	}]
}
